package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel on 24/05/2017.
 */
@Entity
@Table(name="agerange")
public class AgeRangeDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idagerange")
    private Long idAgeRange;

    // The name of the age range
    @NotNull
    private String name;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    AgeRangeDTO(){}

    AgeRangeDTO(AgeRangeDTO ageRangeDTO){
        this.idAgeRange = ageRangeDTO.idAgeRange;
        this.name = ageRangeDTO.name;
    }

    AgeRangeDTO(Long idAgeRange, String name){
        this.idAgeRange = idAgeRange;
        this.name = name;
    }

    public Long getIdAgeRange() {
        return idAgeRange;
    }

    public void setIdAgeRange(Long idAgeRange) {
        this.idAgeRange = idAgeRange;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
