package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel on 22/06/2017.
 * Classe DTO permettant de gerer les informations relatives aux EventPricesCategories.
 */
@Table(name = "eventpricescategories")
@Entity
public class EventPricesCategoriesDTO {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    @Id
    @Column(name = "ideventpricescategories")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idEventPricesCategories;

    // The name of the events prices categories
    @NotNull
    private String name;

    // The usage count of the events prices categories
    @Column(name = "usagecount")
    private Long usageCount;

    @NotNull
    private String description;

    public EventPricesCategoriesDTO() {
    }

    public EventPricesCategoriesDTO(Long idEventPricesCategories, String name, Long usageCount, String description) {
        this.idEventPricesCategories = idEventPricesCategories;
        this.name = name;
        this.usageCount = usageCount;
        this.description = description;
    }

    public EventPricesCategoriesDTO(EventPricesCategoriesDTO eventPricesCategoriesDTO) {
        this.idEventPricesCategories = eventPricesCategoriesDTO.idEventPricesCategories;
        this.name = eventPricesCategoriesDTO.name;
        this.usageCount = eventPricesCategoriesDTO.usageCount;
        this.description = eventPricesCategoriesDTO.description;
    }

    public Long getIdEventPricesCategories() {
        return idEventPricesCategories;
    }

    public void setIdEventPricesCategories(Long idEventPricesCategories) {
        this.idEventPricesCategories = idEventPricesCategories;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getUsageCount() {
        return usageCount;
    }

    public void setUsageCount(Long usageCount) {
        this.usageCount = usageCount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
