package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Date;

/**
 * Created by kprim on 02/03/2017.
 * Classe DTO permettant de gerer les informations relatives aux Event.
 */
@Entity
@Table(name = "Event")
public class EventDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    @Id
    @Column(name = "idevent")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long idEvent;

    // The event's title
    @NotNull
    @Column(name = "title")
    private String title;

    // The event's picture
    @Column(name = "picture")
    private String picture;

    // The event's description
    @NotNull
    @Column(name = "description")
    private String description;

    // The event's type (atelier, formation, etc...)
    @NotNull
    @Column(name = "ideventtype")
    private long idEventType;

    // The event periodicity
    @NotNull
    @Column(name = "allday")
    private boolean allDay;

    // The event's start date
    @NotNull
    @Column(name = "startdate")
    @Temporal(TemporalType.DATE)
    private Date startDate;

    // The event's end date
    @NotNull
    @Column(name = "enddate")
    @Temporal(TemporalType.DATE)
    private Date endDate;

    // The event's start time
    @Column(name = "startat")
    @Temporal(TemporalType.TIMESTAMP)
    private Date startAt;

    // The event's end time
    @Column(name = "endat")
    @Temporal(TemporalType.TIMESTAMP)
    private Date endAt;

    // The recurrence type of the event
    // (in case the event is recurrent... daily, weekly, monthly etc...)
    @NotNull
    @Column(name="idrecurrence")
    private long idRecurrence;

    @Column(name="endrecurrence")
    private Date endRecurrence;

    // The event's price
    @Column(name="standardprice")
    private float standardPrice;

    // Fare reduction
    @Column(name="reducedfare")
    private float reducedFare;

    // Available tickets for this event
    @Column(name = "nbtickets")
    private int nbTickets;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public EventDTO() { }

    public EventDTO(EventDTO event) {
        this.idEvent = event.idEvent;
        this.title = event.title;
        this.picture = event.picture;
        this.description = event.description;
        this.idEventType = event.idEventType;
        this.allDay = event.allDay;
        this.startDate = event.startDate;
        this.endDate = event.endDate;
        this.startAt = event.startAt;
        this.endAt = event.endAt;
        this.idRecurrence = event.idRecurrence;
        this.endRecurrence = event.endRecurrence;
        this.standardPrice = event.standardPrice;
        this.reducedFare = event.reducedFare;
        this.nbTickets = event.nbTickets;
    }

    public EventDTO(long idEvent, String title, String picture, String description, long idEventType, boolean allDay, Date startDate, Date endDate, Date startAt, Date endAt, long idRecurrence, Date endRecurrence, float standardPrice, float reducedFare, int nbTickets ) {
        this.idEvent = idEvent;
        this.title = title;
        this.picture = picture;
        this.description = description;
        this.idEventType = idEventType;
        this.allDay = allDay;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startAt = startAt;
        this.endAt = endAt;
        this.idRecurrence = idRecurrence;
        this.endRecurrence =  endRecurrence;
        this.standardPrice = standardPrice;
        this.reducedFare =  reducedFare;
        this.nbTickets = nbTickets;
    }

    // Getter and setter methods


    public long getIdEvent() {
        return idEvent;
    }

    public void setIdEvent(long idEvent) {
        this.idEvent = idEvent;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getIdEventType() {
        return idEventType;
    }

    public void setIdEventType(long idEventType) {
        this.idEventType = idEventType;
    }

    public boolean isAllDay() {
        return allDay;
    }

    public void setAllDay(boolean allDay) {
        this.allDay = allDay;
    }

    public Date getStartDate() {
        return startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getStartAt() {
        return startAt;
    }

    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }

    public Date getEndAt() {
        return endAt;
    }

    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    public long getIdRecurrence() {
        return idRecurrence;
    }

    public void setIdRecurrence(long idRecurrence) {
        this.idRecurrence = idRecurrence;
    }

    public Date getEndRecurrence() {
        return endRecurrence;
    }

    public void setEndRecurrence(Date endRecurrence) {
        this.endRecurrence = endRecurrence;
    }

    public float getStandardPrice() {
        return standardPrice;
    }

    public void setStandardPrice(float standardPrice) {
        this.standardPrice = standardPrice;
    }

    public float getReducedFare() {
        return reducedFare;
    }

    public void setReducedFare(float reducedFare) {
        this.reducedFare = reducedFare;
    }

    public int getNbTickets() {
        return nbTickets;
    }

    public void setNbTickets(int nbTickets) {
        this.nbTickets = nbTickets;
    }
}
