package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by kprim on 02/03/2017.
 */
@Entity
@Table(name = "eventtype")
public class EventTypeDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event type in the db)
    @Id
    @Column(name = "ideventtype")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long idEventType;

    // The event type label
    @NotNull
    @Column(name = "libelle")
    private String libelle;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public EventTypeDTO() { }

    public EventTypeDTO(EventTypeDTO eventType) {
        this.idEventType = eventType.idEventType;
        this.libelle = eventType.libelle;
    }

    public EventTypeDTO(long idEventType, String libelle) {
        this.idEventType = idEventType;
        this.libelle = libelle;
    }

    // Getter and setter methods

    public long getIdEventType() {
        return idEventType;
    }

    public void setIdEventType(long idEventType) {
        this.idEventType = idEventType;
    }

    public String getLibelle() {
        return libelle;
    }

    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
}
