package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel on 24/05/2017.
 */
@Entity
@Table(name = "eventtheme")
public class EventThemeDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "ideventtheme")
    private Long idEventTheme;

    // The name of the event's theme
    @NotNull
    private String name;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    EventThemeDTO(){}

    EventThemeDTO(EventThemeDTO eventThemeDTO){
        this.idEventTheme = eventThemeDTO.idEventTheme;
        this.name = eventThemeDTO.name;
    }

    EventThemeDTO(Long idEventTheme, String name){
        this.idEventTheme = idEventTheme;
        this.name = name;
    }

    public Long getIdEventTheme() {
        return idEventTheme;
    }

    public void setIdEventTheme(Long idEventTheme) {
        this.idEventTheme = idEventTheme;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
