package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel HANAFI on 29/03/2017.
 */
@Entity
@Table(name = "Licence")
public class LicenceDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idlicence")
    private Long idLicence;

    // The licence's name
    private String name;

    // The licence's description
    private String description;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    LicenceDTO(){}

    LicenceDTO(Long idLicence){this.idLicence = idLicence;}

    LicenceDTO(LicenceDTO licence){
        this.idLicence = licence.idLicence;
        this.name = licence.name;
        this.description = licence.description;
    }

    public Long getIdLicence() {
        return idLicence;
    }

    public void setIdLicence(Long idLicence) {
        this.idLicence = idLicence;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
