package org.fablab.labank.dto;

import javax.persistence.*;
import java.util.List;
import javax.validation.constraints.NotNull;

/**
 * Created by kprim on 27/02/2017.
 */
@Entity
@Table(name = "Machine")
public class MachineDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // The machine's name
    @NotNull
    @Column(name = "name")
    private String name;

    // The machine's description
    @NotNull
    @Column(name = "description")
    private String description;

    // The machine's specification
    @NotNull
    @Column(name = "specification")
    private String specification;

    // The machine's illustration
    @Column(name = "illustration")
    private String illustration;

    // List of files
    @OneToMany
    @JoinTable
    (
        name="machine_has_docmachine",
        joinColumns={ @JoinColumn(name="idmachine", referencedColumnName="id") },
        inverseJoinColumns={ @JoinColumn(name="iddocmachine", referencedColumnName="iddocmachine", unique=true) }
    )
    // While Update this will also insert collection row another insert
    private List<MachineManualDTO> machinemanual;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------
    public MachineDTO() { }

    public MachineDTO(Long id) {
        this.id = id;
    }

    public MachineDTO(MachineDTO machine) {
        this.id = machine.id;
        this.name = machine.name;
        this.description = machine.description;
        this.specification = machine.specification;
        this.illustration = machine.illustration;
    }

    // Getter and setter methods

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getSpecification() {
        return specification;
    }

    public void setSpecification(String specification) {
        this.specification = specification;
    }

    public String getIllustration() {
        return illustration;
    }

    public void setIllustration(String illustration) {
        this.illustration = illustration;
    }

    public List<MachineManualDTO> getMachinemanual() {
        return machinemanual;
    }

    public void setMachinemanual(List<MachineManualDTO> machinemanual) {
        this.machinemanual = machinemanual;
    }

}
