package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel HANAFI on 29/03/2017.
 */
@Entity
@Table(name = "Matrerial")
public class MaterialDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idmaterial")
    private Long idMaterial;

    // The material's name
    @NotNull
    private String name;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    MaterialDTO(){}

    MaterialDTO(Long idMaterial){this.idMaterial = idMaterial;}

    MaterialDTO(MaterialDTO material){
        this.idMaterial = material.idMaterial;
        this.name = material.name;
    }

    public Long getIdMaterial() {
        return idMaterial;
    }

    public void setIdMaterial(Long idMaterial) {
        this.idMaterial = idMaterial;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
