package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * Created by Kandel on 29/06/2017.
 * Classe DTO permettant de gerer les informations relatives aux PricesCategories.
 */
@Entity
@Table(name = "pricescategories")
public class PricesCategoriesDTO {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    @Id
    @Column(name = "idpricescategories")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idPricesCategories;

    // The name of the events prices categories
    @NotNull
    private String name;

    // The usage count of the events prices categories
    @Column(name = "usagecount")
    private Long usageCount;

    @NotNull
    private String description;

    @OneToMany(mappedBy = "pricesCat")
    private List<EventPricesCategoriesDTO> eventPricesCategories;

    public PricesCategoriesDTO() {
    }

    public PricesCategoriesDTO(Long idEventPricesCategories, String name, Long usageCount, String description) {
        this.idPricesCategories = idEventPricesCategories;
        this.name = name;
        this.usageCount = usageCount;
        this.description = description;
    }

    public PricesCategoriesDTO(PricesCategoriesDTO pricesCategoriesDTO) {
        this.idPricesCategories = pricesCategoriesDTO.idPricesCategories;
        this.name = pricesCategoriesDTO.name;
        this.usageCount = pricesCategoriesDTO.usageCount;
        this.description = pricesCategoriesDTO.description;
    }

    public Long getIdPricesCategories() {
        return idPricesCategories;
    }

    public void setIdPricesCategories(Long idPricesCategories) {
        this.idPricesCategories = idPricesCategories;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getUsageCount() {
        return usageCount;
    }

    public void setUsageCount(Long usageCount) {
        this.usageCount = usageCount;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
