package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel HANAFI on 29/03/2017.
 */
@Entity
@Table(name="projectfile")
public class ProjectFileDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idprojectfile")
    private Long idProjectFile;

    @NotNull
    @Column(name = "filename")
    private String fileName;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    ProjectFileDTO(){}

    ProjectFileDTO(Long idProjectFile){this.idProjectFile = idProjectFile;}

    ProjectFileDTO(ProjectFileDTO projectFile){
        this.idProjectFile = projectFile.idProjectFile;
        this.fileName = projectFile.fileName;
    }

    public Long getIdProjectFile() {
        return idProjectFile;
    }

    public void setIdProjectFile(Long idProjectFile) {
        this.idProjectFile = idProjectFile;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}
