package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel on 10/05/2017.
 */
@Entity
@Table(name = "spacefile" )
public class SpaceFileDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idspacefile")
    private Long idSpaceFile;


    @NotNull
    @Column(name="filename")
    private String fileName;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------


    public SpaceFileDTO() {
    }

    public SpaceFileDTO(Long idSpaceFile) {
        this.idSpaceFile = idSpaceFile;
    }

    public SpaceFileDTO(SpaceFileDTO spaceFile) {
        this.idSpaceFile = spaceFile.idSpaceFile;
        this.fileName = spaceFile.fileName;
    }

    public Long getIdSpaceFile() {
        return idSpaceFile;
    }

    public void setIdSpaceFile(Long idSpaceFile) {
        this.idSpaceFile = idSpaceFile;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}
