package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * Created by Kandel on 10/05/2017.
 */
@Entity()
@Table(name="Space")
public class SpaceDTO {
    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "idspace")
    private Long idSpace;

    // The space's name
    @NotNull
    private String name;

    // The space's illustraion
    @NotNull
    private String illustration;

    // The numbers of tickets for the space
    @Column(name="maxtickets")
    private Long maxTickets;

    // The space's description
    @NotNull
    private String description;

    // The space's characteristic
    @Column(name = "characteristics")
    private String characteristic;

    // List of space's files
    @OneToMany
    @JoinTable
    (
        name="space_has_files",
        joinColumns={ @JoinColumn(name="space_idspace", referencedColumnName="idspace") },
        inverseJoinColumns={ @JoinColumn(name="spacefile_idspacefile", referencedColumnName="idspacefile", unique=true) }
    )
    // While Update this will also insert collection row another insert
    private List<SpaceFileDTO> spaceFiles;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------


    public SpaceDTO() {
    }

    public SpaceDTO(Long idSpace) {
        this.idSpace = idSpace;
    }

    public SpaceDTO(SpaceDTO space){
        this.idSpace = space.idSpace;
        this.name = space.name;
        this.illustration = space.illustration;
        this.maxTickets = space.maxTickets;
        this.description = space.description;
        this.characteristic = space.characteristic;
    }

    public Long getIdSpace() {
        return idSpace;
    }

    public void setIdSpace(Long idSpace) {
        this.idSpace = idSpace;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIllustration() {
        return illustration;
    }

    public void setIllustration(String illustration) {
        this.illustration = illustration;
    }

    public Long getMaxTickets() {
        return maxTickets;
    }

    public void setMaxTickets(Long maxTickets) {
        this.maxTickets = maxTickets;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCharacteristic() {
        return characteristic;
    }

    public void setCharacteristic(String characteristic) {
        this.characteristic = characteristic;
    }

    public List<SpaceFileDTO> getSpaceFiles() {
        return spaceFiles;
    }

    public void setSpaceFiles(List<SpaceFileDTO> spaceFiles) {
        this.spaceFiles = spaceFiles;
    }
}
