package org.fablab.labank.dto;

import org.springframework.web.bind.annotation.RestController;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel HANAFI on 30/03/2017.
 * Classe DTO permettant de gerer les informations relatives aux Step.
 */
@Entity
@Table(name = "Step")
public class StepDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    @Id
    @Column(name = "idstep")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idStep;

    @NotNull
    @Column(name = "idproject")
    private Long idProject;

    @NotNull
    private String title;

    private String description;

    @NotNull
    private Long order;

    private String picture;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    StepDTO(){}

    StepDTO(Long idStep){this.idStep = idStep;}

    StepDTO(StepDTO step){
        this.idStep = step.idStep;
        this.title = step.title;
        this.idProject = step.idProject;
        this.description = step.description;
        this.order = step.order;
        this.picture = step.picture;
    }

    public Long getIdStep() {
        return idStep;
    }

    public void setIdStep(Long idStep) {
        this.idStep = idStep;
    }

    public Long getIdProject() {
        return idProject;
    }

    public void setIdProject(Long idProject) {
        this.idProject = idProject;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getOrder() {
        return order;
    }

    public void setOrder(Long order) {
        this.order = order;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }
}
