package org.fablab.labank.dto;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel HANAFI on 30/03/2017.
 * Classe DTO permettant de gerer les informations relatives aux Step.
 */
@Entity
@Table(name = "Step")
public class StepDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each event in the db)
    @Id
    @Column(name = "idstep")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idStep;

//    @NotNull
//    @Column(name = "idproject")
//    private Long idProject;
    @JsonBackReference
    @ManyToOne
    @JoinColumn(name = "idproject", referencedColumnName = "idproject")
    private ProjectDTO project;

    @NotNull
    private String title;

    private String description;

    @NotNull
    @Column(name = "stepsorder")
    private Long stepsOrder;

    private String illustration;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    StepDTO(){}

    StepDTO(Long idStep){this.idStep = idStep;}

    StepDTO(StepDTO step){
        this.idStep = step.idStep;
        this.title = step.title;
        this.project = step.project;
        this.description = step.description;
        this.stepsOrder = step.stepsOrder;
        this.illustration = step.illustration;
    }

    public Long getIdStep() {
        return idStep;
    }

    public void setIdStep(Long idStep) {
        this.idStep = idStep;
    }

    public ProjectDTO getProject() {
        return project;
    }

    public void setProject(ProjectDTO project) {
        this.project = project;
    }

    //    public Long getIdProject() {
    //        return idProject;
    //    }
    //
    //    public void setIdProject(Long idProject) {
    //        this.idProject = idProject;
    //    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getStepsOrder() {
        return stepsOrder;
    }

    public void setStepsOrder(Long stepsOrder) {
        this.stepsOrder = stepsOrder;
    }

    public String getIllustration() {
        return illustration;
    }

    public void setIllustration(String illustration) {
        this.illustration = illustration;
    }
}
