package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by Kandel HANAFI on 29/03/2017.
 */
@Entity
@Table(name = "Theme")
public class ThemeDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="idtheme")
    private Long idTheme;

    // The theme's name
    @NotNull
    private String name;

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    ThemeDTO(){}

    ThemeDTO(Long idTheme){this.idTheme = idTheme;}

    ThemeDTO(ThemeDTO theme){
        this.idTheme = theme.idTheme;
        this.name = theme.name;
    }

    public Long getIdTheme() {
        return idTheme;
    }

    public void setIdTheme(Long idTheme) {
        this.idTheme = idTheme;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
