/**
 * Created by Kandel HANAFI on 03/03/2017.
 * Classe DTO permettant de gerer les informations relatives aux Training.
 */
package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.List;

@Entity
@Table(name="Training")
public class TrainingDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)

    @Id
    @Column(name="idtraining")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // The training's name
    @NotNull
    private String name;

    //The training's illustration (URL of the image)
    @NotNull
    private String illustration;

    // The training's description
    @NotNull
    private String description;

    // The number of available tickets
    @Column(name = "nbticket")
    private Long nbTicket;

    // Booelan that indicates if the training has to be displayed
    @NotNull
    private boolean display;

    // Available tickets for this event
    @Column(name = "availabletickets")
    private int availableTickets;

    // Facebook share
    @Column(name = "facebookshare")
    private int facebookShare;

    // Twitter share
    @Column(name = "twittershare")
    private int twitterShare;

    // Likes
    private int likes;

    // List of associated machine (user can associate a machine to a training)
    @OneToMany
    @JoinTable
    (
        name="associatedmachine",
        joinColumns={ @JoinColumn(name="training_idtraining", referencedColumnName="idtraining") },
        inverseJoinColumns={ @JoinColumn(name="machine_idmachine", referencedColumnName="id", unique=true) }
    )
    // While Update this will also insert collection row another insert
    private List<MachineDTO> associatedMachines;



    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public TrainingDTO(){}

    public TrainingDTO(Long id) {
        this.id = id;
    }

    public TrainingDTO (TrainingDTO trainingDTO){
        this.id = trainingDTO.id;
        this.illustration = trainingDTO.illustration;
        this.description = trainingDTO.description;
        this.nbTicket = trainingDTO.nbTicket;
        this.display = trainingDTO.display;
        this.availableTickets = trainingDTO.availableTickets;
        this.facebookShare = trainingDTO.facebookShare;
        this.twitterShare = trainingDTO.twitterShare;
        this.likes = trainingDTO.likes;
    }

    /** Getter and Setters **/
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIllustration() {
        return illustration;
    }

    public void setIllustration(String illustration) {
        this.illustration = illustration;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getNbTicket() {
        return nbTicket;
    }

    public void setNbTicket(Long nbTicket) {
        this.nbTicket = nbTicket;
    }

    public boolean isDisplay() {
        return display;
    }

    public void setDisplay(boolean display) {
        this.display = display;
    }

    public int getAvailableTickets() {
        return availableTickets;
    }

    public void setAvailableTickets(int availableTickets) {
        this.availableTickets = availableTickets;
    }

    public int getFacebookShare() {
        return facebookShare;
    }

    public void setFacebookShare(int facebookShare) {
        this.facebookShare = facebookShare;
    }

    public int getTwitterShare() {
        return twitterShare;
    }

    public void setTwitterShare(int twitterShare) {
        this.twitterShare = twitterShare;
    }

    public int getLikes() {
        return likes;
    }

    public void setLikes(int likes) {
        this.likes = likes;
    }

    public List<MachineDTO> getAssociatedMachines() {
        return associatedMachines;
    }

    public void setAssociatedMachines(List<MachineDTO> associatedMachines) {
        this.associatedMachines = associatedMachines;
    }
}
