package org.fablab.labank.dto;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Created by kprim on 17/01/2017.
 */

@Entity
@Table(name = "User")
public class UserDTO {

    // ------------------------
    // PRIVATE FIELDS
    // ------------------------

    // An autogenerated id (unique for each user in the db)
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    // The user's Sex
    @NotNull
    @Column(name = "sex")
    private char sex;

    // The user's pseudonym
    @NotNull
    @Column(name = "pseudonym")
    private String pseudonym;

    // The user's password
    @NotNull
    private String password;

    // The user's name
    @NotNull
    private String name;

    // The user's firstname
    @NotNull
    private String firstname;

    // The user's email
    // TODO : Add spring annotation validator to validate email format
    @NotNull
    private String email;

    // The user's date of birth
    @NotNull
    private Date birthday;

    // The user's address
    private String address;

    // The user's phone number
    @NotNull
    @Size(min=10,max=10)
    @Pattern(regexp="(^$|[0-9]{10})")
    private String phone;

    // The user's website
    // TODO :  Add spring annotation to validate website address format
    private String website;

    // The user's occupation
    private String occupation;

    // The user's interests
    private String interests;

    // The user's groupId ID
//    @OneToOne
//    @JoinColumn(name = "groupid")
    @Column(name = "groupid")
    @NotNull
    private Long groupId;

    // The user's profile ID
    @OneToOne
    @JoinColumn(name = "profileid")
    @NotNull
    private Profile profile;

    // The user's avatar
    private String avatar;

    // The user's public secret
    @Transient
    private String publicSecret;

    // The user's private secret
    @Transient
    private String privateSecret;

    // The user's authorities
    @Transient
    List<String> authorities = new ArrayList<>();

    // ------------------------
    // PUBLIC METHODS
    // ------------------------

    public UserDTO() { }

    public UserDTO(UserDTO userDTO){
        this.id = userDTO.id;
        this.sex = userDTO.sex;
        this.pseudonym = userDTO.pseudonym;
        this.password = userDTO.password;
        this.email = userDTO.email;
        this.name = userDTO.name;
        this.firstname = userDTO.firstname;
        this.birthday = userDTO.birthday;
        this.address = userDTO.address;
        this.phone = userDTO.phone;
        this.website = userDTO.website;
        this.occupation = userDTO.occupation;
        this.interests = userDTO.interests;
        this.groupId = userDTO.groupId;
        this.profile = userDTO.profile;
        this.avatar = userDTO.avatar;
    }

    public UserDTO(long id) {
        this.id = id;
    }

    public UserDTO(char sex, String pseudonym, String password, String email, String name, String firstname, Date birthday, String address, String phone, String website, String occupation, String interests, Long groupId, Profile profile, String avatar) {
        this.sex = sex;
        this.pseudonym = pseudonym;
        this.password = password;
        this.email = email;
        this.name = name;
        this.firstname = firstname;
        this.birthday = birthday;
        this.address = address;
        this.phone = phone;
        this.website = website;
        this.occupation = occupation;
        this.interests = interests;
        this.groupId = groupId;
        this.profile = profile;
        this.avatar = avatar;
    }

    // Getter and setter methods

    public long getId() {
        return id;
    }

    public void setId(long value) {
        this.id = value;
    }

    public char getSex() { return sex; }

    public void setSex(char sex) { this.sex = sex; }

    public String getEmail() {
        return email;
    }

    public void setEmail(String value) {
        this.email = value;
    }

    public String getName() {
        return name;
    }

    public void setName(String value) {
        this.name = value;
    }

    public String getPseudonym() {
        return pseudonym;
    }

    public void setPseudonym(String pseudonym) {
        this.pseudonym = pseudonym;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public Date getDateOfBirth() {
        return birthday;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.birthday = dateOfBirth;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhoneNumber() {
        return phone;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phone = phoneNumber;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getOccupation() {
        return occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getInterests() {
        return interests;
    }

    public void setInterests(String interests) {
        this.interests = interests;
    }

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public Profile getProfile() {
        return profile;
    }

    public void setProfile(Profile profile) {
        this.profile = profile;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPublicSecret() {
        return publicSecret;
    }

    public void setPublicSecret(String publicSecret) {
        this.publicSecret = publicSecret;
    }

    public void setPrivateSecret(String privateSecret) {
        this.privateSecret = privateSecret;
    }

    public String getPrivateSecret() {
        return privateSecret;
    }

    public void setAuthorities(List<String> authorities) {
        this.authorities = authorities;
    }

    public List<String> getAuthorities() {
        return authorities;
    }
} // class UserDTO